# https://scipy.org/      search in google

# https://www.numpy.org

# https://www.numpy.org/devdocs/user/quickstart.html

### Numpy Library
- Processing N-Dimensional arrays

In [2]:
import numpy as np

li = [1,2,3]

a=np.array(li)
type(a)

numpy.ndarray

In [3]:
import numpy as np

li = [1,2,3,'z']

a=np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

In [4]:
import numpy as np

li = [1,2,3,'z']

a=np.array(li)

b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [6]:
rn= np.random.randint(0,100,size=10)
rn


array([22,  6, 15, 19, 47, 30, 26, 31, 15, 41])

In [7]:
# For 3-Dimensional matrix

m3 = np.random.randint(0,1,size=(3,3))
m3

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [8]:
m3 = np.random.randint(0,2,size=(3,3))
m3

array([[1, 1, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [9]:
m3 = np.random.randint(0,2,size=(10,10))
m3

array([[1, 1, 1, 0, 1, 0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0, 1, 1, 1],
       [1, 0, 1, 1, 1, 1, 0, 0, 1, 1],
       [0, 0, 1, 1, 1, 0, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 1, 1],
       [1, 1, 1, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 0, 1, 1, 0]])

In [10]:
# 3-Dimensional data
m3 = np.random.randint(0,2,size=(3,3,3))
m3

array([[[0, 0, 0],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 0, 1],
        [1, 0, 0],
        [1, 0, 0]],

       [[1, 1, 0],
        [0, 1, 1],
        [1, 1, 1]]])

In [12]:
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3

array([[[[0, 0, 1],
         [0, 1, 0],
         [1, 1, 1]],

        [[1, 0, 0],
         [0, 1, 1],
         [0, 0, 1]],

        [[1, 1, 1],
         [1, 1, 1],
         [0, 1, 1]]],


       [[[1, 1, 0],
         [1, 0, 0],
         [0, 0, 0]],

        [[1, 0, 1],
         [0, 1, 0],
         [0, 1, 0]],

        [[1, 0, 1],
         [1, 1, 0],
         [1, 1, 0]]],


       [[[1, 0, 1],
         [0, 0, 0],
         [0, 0, 0]],

        [[1, 0, 0],
         [0, 0, 1],
         [1, 0, 0]],

        [[0, 1, 1],
         [0, 0, 1],
         [0, 0, 0]]]])

In [16]:
m3 = np.random.randint(0,2,size=(3,3,3,3))
m3[2][2][2][1]


1

In [17]:
m3.ndim

4

In [18]:
m3.size

81

In [19]:
m3.shape

(3, 3, 3, 3)

In [20]:
m3.dtype

dtype('int32')

In [21]:
m3.itemsize

4

In [22]:
m3.nbytes

324

### GitHub repository of Akash sir
- PythonDataScienceHandbook

In [23]:
print(b)   # print will remove all comas(,)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [25]:
b.reshape(10,3)

ValueError: cannot reshape array of size 15 into shape (10,3)

In [26]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [27]:
import numpy as np
M=np.ones((3,3))
print("Matrix M: \n",M)

Matrix M: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


### Pandas

- Data Cleaning
- Data Transformation
- Data Analysis

**Notations**
- series   --> 1D  it is a row
- DataFrames --> table

In [2]:
import pandas as pd

internal1 = {'s1':21, 's2':18, 's3':24}

internal1 = pd.Series(internal1)

internal2 = {'s1':15,'s2':18,'s3':12}
internal2 = pd.Series(internal2)
internal2


s1    15
s2    18
s3    12
dtype: int64

In [4]:
final = {'internal1':internal1, 'internal2':internal2}

final = pd.DataFrame(final)
final

internal1  internal2
s1         21         15
s2         18         18
s3         24         12

In [10]:
final = {'internal1':internal1, 'internal2':internal2}

final = pd.DataFrame(final)
final['internal1']

s1    21
s2    18
s3    24
Name: internal1, dtype: int64

In [8]:
final.columns  # Name of all columns

Index(['internal1', 'internal2'], dtype='object')

In [9]:
final.values  # Lists of all rows


array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [11]:
final.values[2]   # accessing the 2nd row i.e 3 rd row i.e 0-1-2

array([24, 12], dtype=int64)

In [12]:
final.values[2,0]  # 3 row 1st column 

24

In [13]:
final.values[2][0]

24

In [16]:
for row in final.values:
    print('internal1 -',row[0],', internal2 -',row[1])

internal1 - 21 , internal2 - 15
internal1 - 18 , internal2 - 18
internal1 - 24 , internal2 - 12


In [17]:
final

internal1  internal2
s1         21         15
s2         18         18
s3         24         12

In [20]:
final.loc['3'] = [11, 10]
final

internal1  internal2
s1         21         15
s2         18         18
s3         24         12
3          11         10
s4         11         10
3          11         10

In [21]:
final.drop(3)

internal1  internal2
s1         21         15
s2         18         18
s3         24         12
s4         11         10
3          11         10

In [22]:
final.drop(3)

internal1  internal2
s1         21         15
s2         18         18
s3         24         12
s4         11         10
3          11         10

In [23]:
final.values[2,0] = 25
final

internal1  internal2
s1         21         15
s2         18         18
s3         25         12
3          11         10
s4         11         10
3          11         10

In [24]:
final

internal1  internal2
s1         21         15
s2         18         18
s3         25         12
3          11         10
s4         11         10
3          11         10

In [25]:
final.values[2] = [12,25]

In [26]:
final

internal1  internal2
s1         21         15
s2         18         18
s3         12         25
3          11         10
s4         11         10
3          11         10

In [27]:
final.drop(3)

internal1  internal2
s1         21         15
s2         18         18
s3         12         25
s4         11         10
3          11         10

In [2]:
# Reading CSV file data
import pandas as pd
filepath = 'DataFiles/Income.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [4]:
# Extracting all The states income in the year 2013
for row in incomedf.values:
    print('state -',row[1],':','yearIncome-',row[-1])

state - Alabama : yearIncome- 41381
state - Alaska : yearIncome- 61137
state - Arizona : yearIncome- 50602
state - Arkansas : yearIncome- 39919
state - California : yearIncome- 57528


In [7]:
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [6]:
# Extracting all The states income in the year 2013
for row in incomedf.values:
    print(row[1],':',row[-1])

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [9]:
# Extracting all income data in the year 2009
for row in incomedf.values:
    print(row[1],':',row[-5])

Alabama : 39980
Alaska : 61604
Arizona : 45739
Arkansas : 36538
California : 56134


In [12]:
# Average income of the state Arizona
sum = 0
for i in range(2,11):
    sum +=incomedf.values[2][i]

    
sum/len(incomedf.values[2][2:])

48967.88888888889

In [14]:
# Average income of the year 2012

sum=0
for row in incomedf.values:
    sum +=row[-2]
sum/len(incomedf.values)

50038.8

In [15]:
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [18]:
# each row is a value, here we have 5 values means 5 rows 
# in that each row --->  row[0][-2] means 1st row last but one i.e 43464
incomedf.values

array([['04000US01', 'Alabama', 37150, 37952, 42212, 44476, 39980, 40933,
        42590, 43464, 41381],
       ['04000US02', 'Alaska', 55891, 56418, 62993, 63989, 61604, 57848,
        57431, 63648, 61137],
       ['04000US04', 'Arizona', 45245, 46657, 62993, 46914, 45739, 46896,
        48621, 47044, 50602],
       ['04000US05', 'Arkansas', 36658, 37057, 40795, 39586, 36538,
        38587, 41302, 39018, 39919],
       ['04000US06', 'California', 51755, 55319, 55734, 57014, 56134,
        54283, 53367, 57020, 57528]], dtype=object)